# Fantasy Expert

In [153]:
# IMPORTS
import pandas as pd
import nflreadpy as nfl
pd.set_option('display.max_rows', None)

df = nfl.load_player_stats(seasons=[2023,2024,2025], summary_level='week').to_pandas()
df[df['position'] == 'QB'].head(3)

,player_id,player_name,player_display_name,position,position_group,headshot_url,season,week,season_type,game_id,team,opponent_team,completions,attempts,passing_yards,passing_tds,passing_interceptions,sacks_suffered,sack_yards_lost,sack_fumbles,sack_fumbles_lost,passing_air_yards,passing_yards_after_catch,passing_first_downs,passing_epa,passing_cpoe,passing_2pt_conversions,pacr,passing_10,passing_16,passing_20,passing_40,carries,rushing_yards,rushing_tds,rushing_fumbles,rushing_fumbles_lost,rushing_first_downs,rushing_epa,rushing_2pt_conversions,rushing_10,rushing_12,rushing_20,rushing_40,receptions,targets,receiving_yards,receiving_tds,receiving_fumbles,receiving_fumbles_lost,receiving_air_yards,receiving_yards_after_catch,receiving_first_downs,receiving_epa,receiving_2pt_conversions,receiving_10,receiving_16,receiving_20,receiving_40,racr,target_share,air_yards_share,wopr,special_teams_tds,def_tackles_solo,def_tackles_with_assist,def_tackle_assists,def_tackles_for_loss,def_tackles_for_loss_yards,def_fumbles_forced,def_sacks,def_sack_yards,def_qb_hits,def_interceptions,def_interception_yards,def_pass_defended,def_tds,def_fumbles,def_safeties,misc_yards,fumble_recovery_own,fumble_recovery_yards_own,fumble_recovery_opp,fumble_recovery_yards_opp,fumble_recovery_tds,penalties,penalty_yards,fumbles_forced_by_opp,fumbles_not_forced,fumbles_out_of_bounds,fumbles_total,fumbles_lost_total,punt_returns,punt_return_yards,kickoff_returns,kickoff_return_yards,fg_made,fg_att,fg_missed,fg_blocked,fg_long,fg_pct,fg_made_0_19,fg_made_20_29,fg_made_30_39,fg_made_40_49,fg_made_50_59,fg_made_60_,fg_missed_0_19,fg_missed_20_29,fg_missed_30_39,fg_missed_40_49,fg_missed_50_59,fg_missed_60_,fg_made_list,fg_missed_list,fg_blocked_list,fg_made_distance,fg_missed_distance,fg_blocked_distance,pat_made,pat_att,pat_missed,pat_blocked,pat_pct,gwfg_made,gwfg_att,gwfg_missed,gwfg_blocked,gwfg_distance,pt_att,pt_blocked,pt_long,pt_yards,pt_inside_20,pt_out_of_bounds,pt_downed,pt_touchback,pt_fair_caught,pt_returned,pt_return_yards,pt_return_tds,pt_net_yards,fantasy_points,fantasy_points_ppr
0,00-0023459,A.Rodgers,Aaron Rodgers,QB,QB,https://static.www.nfl.com/image/upload/f_auto...,2023,1,REG,2023_01_BUF_NYJ,NYJ,BUF,0,1,0,0,0,1,-10,0,0,17,0,0,-2.031960,NaN,0,0.000000,0,0,0,0,0,0,0,0,0,0,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,0,0,0,0,0,NaN,0.0,0.0,0.0,0,0,0,0,0,0,0,0.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,None,None,None,0,0,0,0,0,0,0,NaN,0,0,0,0,0,0,0,NaN,0,0,0,0,0,0,0,0,0,0,0.00,0.00
4,00-0026498,M.Stafford,Matthew Stafford,QB,QB,https://static.www.nfl.com/image/upload/f_auto...,2023,1,REG,2023_01_LA_SEA,LA,SEA,24,38,334,0,0,0,0,0,0,409,106,17,20.679982,-0.425926,0,0.816626,18,7,6,1,3,11,0,0,0,1,0.868086,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,0,0,0,0,0,NaN,0.0,0.0,0.0,0,0,0,0,0,0,0,0.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,None,None,None,0,0,0,0,0,0,0,NaN,0,0,0,0,0,0,0,NaN,0,0,0,0,0,0,0,0,0,0,14.46,14.46
15,00-0028118,T.Taylor,Tyrod Taylor,QB,QB,https://static.www.nfl.com/image/upload/f_auto...,2023,1,REG,2023_01_DAL_NYG,NYG,DAL,2,2,6,0,0,0,0,0,0,-10,16,0,-0.544657,11.933872,0,0.000000,0,0,0,0,0,0,0,0,0,0,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,0,0,0,0,0,NaN,0.0,0.0,0.0,0,0,0,0,0,0,0,0.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,None,None,None,0,0,0,0,0,0,0,NaN,0,0,0,0,0,0,0,NaN,0,0,0,0,0,0,0,0,0,0,0.24,0.24

In [156]:
# FEATURE ENGINEERING

# Weighted Opportunities
df['wopr'] = (1.5*df['target_share']) + (0.7*df['air_yards_share'])

# RB Touches
df['touches'] = df['carries'] + df['targets']

# EWMA Scaled stats
ewma_metrics = ['fantasy_points_ppr', 'wopr', 'targets', 'receptions', 'receiving_yards', 'receiving_air_yards', 'receiving_yards_after_catch', 'receiving_first_downs', 'receiving_10', 'rushing_10','touches','receiving_20', 'target_share', 'air_yards_share', 'carries', 'rushing_yards', 'rushing_tds', 'rushing_first_downs', 'rushing_epa', 'completions', 'passing_yards', 'passing_tds', 'passing_interceptions', 'sacks_suffered', 'pacr', 'passing_epa', 'passing_cpoe', 'attempts']
for col in ewma_metrics:
    df[f'{col}_ewma3'] = df.groupby('player_id')[col].transform(lambda x: x.shift(1).ewm(span=4, min_periods=1).mean())

# Prior season performance
prior_season_avg = df.groupby(['player_id', 'season'])['fantasy_points_ppr'].mean().reset_index()
prior_season_avg['season'] += 1
prior_season_avg = prior_season_avg.rename(columns={'fantasy_points_ppr': 'prior_season_ppg'})
df = df.drop(columns=['prior_season_ppg'], errors='ignore')
df = df.merge(prior_season_avg, on=['player_id', 'season'], how='left')
df['prior_season_ppg'] = df['prior_season_ppg'].fillna(0)  # or fillna with league-average rookie WR output

# Boom/Bust likelihood
df['fantasy_points_ppr_std5'] = df.groupby('player_id')['fantasy_points_ppr'].transform(
    lambda x: x.shift(1).rolling(5, min_periods=2).std()
)

# Defense Stats
def_allowed = df.groupby(['opponent_team', 'season', 'week', 'position'])['fantasy_points_ppr'].sum().reset_index().sort_values(['opponent_team', 'position', 'season', 'week'])
def_allowed['def_allowed_l4w'] = def_allowed.groupby(['opponent_team', 'position'])['fantasy_points_ppr'].transform(lambda x: x.shift(1).rolling(4,1).mean())

df = df.drop(columns=['def_allowed_l4w'], errors='ignore')  # NEW — clears any stale version first
df = df.merge(def_allowed[['opponent_team', 'season', 'week', 'position', 'def_allowed_l4w']], on=['opponent_team', 'season', 'week', 'position'], how='left')

# Additions for RBs

In [130]:
# MODEL SETUP
from sklearn.linear_model import LinearRegression
from xgboost import XGBRegressor
from sklearn.metrics import mean_absolute_error, root_mean_squared_error

def rolling_eval(df, feature_cols, target_col, model_factory, test_season = 2025):
    results, preds_list = [], []
    weeks = sorted(df[df.season == test_season].week.unique())

    for week in weeks:
        train = df[(df.season < test_season) | ((df.season == test_season) & (df.week < week))]
        test = df[(df.season == test_season) & (df.week == week)]

        if len(test) < 5: continue

        model = model_factory()
        model.fit(train[feature_cols], train[target_col])
        preds = model.predict(test[feature_cols])

        results.append({'week': week, 'mae': mean_absolute_error(test[target_col], preds), 'n': len(test)})

        week_preds = test[['player_name', 'opponent_team', 'week']].copy()
        week_preds['pred'] = preds
        week_preds['actual'] = test[target_col].values
        preds_list.append(week_preds)
    
    return pd.DataFrame(results), pd.concat(preds_list, ignore_index=True)

## Wide Reciever

In [142]:
feature_cols = ['wopr_ewma3', 'fantasy_points_ppr_ewma3', 'receiving_yards_after_catch_ewma3', 'def_allowed_l4w', 'fantasy_points_ppr_std5', 'prior_season_ppg']

wrs = df[df['position'] == 'WR']
wr_clean_df = wrs.dropna(subset=feature_cols + ['fantasy_points_ppr'])

wr_results, wr_preds = rolling_eval(wr_clean_df, feature_cols, 'fantasy_points_ppr', lambda: XGBRegressor(n_estimators=200, max_depth=4, learning_rate=0.05))
print(f"Overall MAE: {wr_results.mae.mean():.2f}")

Overall MAE: 4.48

In [143]:
wr_preds[wr_preds['player_name'] == 'J.Chase']
# df[feature_cols].corr().round(2)

     player_name opponent_team  week       pred  actual
59       J.Chase           CLE     1  15.716465     4.6
182      J.Chase           JAX     2  16.184948    36.5
306      J.Chase           MIN     3  11.576979     8.9
447      J.Chase           DEN     4  17.399706     7.3
579      J.Chase           DET     5  14.346405    29.0
709      J.Chase            GB     6  13.616754    25.1
837      J.Chase           PIT     7  13.702927    38.1
965      J.Chase           NYJ     8  16.957047    21.1
1089     J.Chase           CHI     9  18.998936    17.1
1341     J.Chase           PIT    11  11.728035     6.0
1604     J.Chase           BAL    13  20.491011    18.0
1747     J.Chase           BUF    14  18.196846    10.2
1876     J.Chase           BAL    15  19.400047    23.2
2019     J.Chase           MIA    16  20.402349    19.9
2168     J.Chase           ARI    17  15.028783    25.0
2308     J.Chase           CLE    18  11.362791    23.6

## Runningback

In [144]:
feature_cols = ['touches_ewma3','target_share_ewma3','fantasy_points_ppr_ewma3','rushing_epa_ewma3','rushing_10_ewma3','def_allowed_l4w','fantasy_points_ppr_std5','prior_season_ppg']

rbs = df[df['position'] == 'RB']
rb_clean_df = rbs.dropna(subset=feature_cols + ['fantasy_points_ppr'])

rb_results, rb_preds = rolling_eval(rb_clean_df, feature_cols, 'fantasy_points_ppr', lambda: XGBRegressor(n_estimators=200, max_depth=4, learning_rate=0.05))
print(f"Overall MAE: {rb_results.mae.mean():.2f}")

Overall MAE: 4.49

In [145]:
rb_preds[rb_preds['player_name'] == 'J.Gibbs']

     player_name opponent_team  week       pred  actual
59       J.Gibbs            GB     1  14.715076    15.0
130      J.Gibbs           CHI     2  20.959639    19.4
199      J.Gibbs           BAL     3  17.610474    26.9
284      J.Gibbs           CLE     4  18.867510    17.7
370      J.Gibbs           CIN     5  16.968605    16.7
452      J.Gibbs            KC     6  18.956060     7.5
532      J.Gibbs            TB     7  13.861901    36.8
685      J.Gibbs           MIN     9  23.684877     5.8
762      J.Gibbs           WAS    10  18.619417    38.2
847      J.Gibbs           PHI    11  18.104088    19.6
926      J.Gibbs           NYG    12  24.123865    55.4
1006     J.Gibbs            GB    13  20.741808    11.6
1092     J.Gibbs           DAL    14  23.932764    37.0
1177     J.Gibbs            LA    15  20.009836     9.8
1268     J.Gibbs           PIT    16  22.971809    22.8
1359     J.Gibbs           MIN    17  17.258101     6.4
1450     J.Gibbs           CHI    18  16.986027    20.3

## Quarterback

In [163]:
feature_cols = [
    'fantasy_points_ppr_ewma3',
    'attempts_ewma3',
    'carries_ewma3',
    'passing_epa_ewma3',
    'passing_cpoe_ewma3',
    'rushing_epa_ewma3',
    'sacks_suffered_ewma3',
    'def_allowed_l4w',
    'fantasy_points_ppr_std5',
    'prior_season_ppg'
]

qbs = df[df['position'] == 'QB']
qb_clean_df = qbs.dropna(subset=feature_cols + ['fantasy_points_ppr'])

qb_results, qb_preds = rolling_eval(qb_clean_df, feature_cols, 'fantasy_points_ppr', lambda: XGBRegressor(n_estimators=100,learning_rate=0.05, max_depth=2, min_child_weight=8, subsample=0.8, colsample_bytree=0.8, reg_lambda=2.0, random_state=42))
print(f"Overall MAE: {qb_results.mae.mean():.2f}")

Overall MAE: 6.58

In [169]:
qb_preds[qb_preds['player_name'] == 'D.Prescott']

    player_name opponent_team  week       pred  actual
5    D.Prescott           PHI     1  13.254861    7.82
37   D.Prescott           NYG     2  12.750929   22.14
78   D.Prescott           CHI     3  16.783636   12.04
113  D.Prescott            GB     4  15.005260   30.96
145  D.Prescott           NYJ     5  17.220589   28.28
178  D.Prescott           CAR     6  18.065849   22.34
216  D.Prescott           WAS     7  18.372723   23.26
250  D.Prescott           DEN     8  18.433359    6.62
280  D.Prescott           ARI     9  17.131075   15.40
347  D.Prescott            LV    11  16.993063   24.32
382  D.Prescott           PHI    12  17.348137   27.06
411  D.Prescott            KC    13  18.451143   20.60
449  D.Prescott           DET    14  17.765680   18.44
481  D.Prescott           MIN    15  17.113489   11.96
519  D.Prescott           LAC    16  17.224350   19.16
559  D.Prescott           WAS    17  17.139271   22.68
596  D.Prescott           NYG    18  17.075045    0.70

## Tight End

In [175]:
feature_cols = ['wopr_ewma3', 'fantasy_points_ppr_ewma3', 'receiving_yards_after_catch_ewma3', 'def_allowed_l4w', 'fantasy_points_ppr_std5', 'prior_season_ppg']

tes = df[df['position'] == 'TE']
te_clean_df = tes.dropna(subset=feature_cols + ['fantasy_points_ppr'])

te_results, te_preds = rolling_eval(te_clean_df, feature_cols, 'fantasy_points_ppr', lambda: XGBRegressor(n_estimators=200, max_depth=4, learning_rate=0.05))
print(f"Overall MAE: {te_results.mae.mean():.2f}")

Overall MAE: 3.78

In [174]:
te_preds[te_preds['player_name'] == 'K.Pitts']

     player_name opponent_team  week       pred  actual
33       K.Pitts            TB     1   8.420631    12.9
98       K.Pitts           MIN     2   7.711556     7.7
155      K.Pitts           CAR     3   8.612337     7.9
229      K.Pitts           WAS     4   8.384114    18.0
363      K.Pitts           BUF     6   8.624454     4.8
434      K.Pitts            SF     7   9.625385    13.2
497      K.Pitts           MIA     8  11.654899    14.9
559      K.Pitts            NE     9  11.044762     7.8
625      K.Pitts           IND    10  10.429636     5.8
694      K.Pitts           CAR    11   8.392801     3.4
763      K.Pitts            NO    12   9.320452     4.5
828      K.Pitts           NYJ    13   9.238132    15.2
907      K.Pitts           SEA    14  14.250237    15.0
975      K.Pitts            TB    15  11.086644    45.6
1053     K.Pitts           ARI    16   8.958734    18.7
1127     K.Pitts            LA    17  13.166815     3.6
1199     K.Pitts            NO    18  11.076839    11.8

## Takeaways
---
The best results thus far are with XGBoost with parameters: (n_estimators=200, max_depth=4, learning_rate=0.05). Optimal features thus far are: 
- ['touches_ewma3','target_share_ewma3','fantasy_points_ppr_ewma3','rushing_epa_ewma3','rushing_10_ewma3','def_allowed_l4w','fantasy_points_ppr_std5','prior_season_ppg'] for RBs
- ['wopr_ewma3', 'fantasy_points_ppr_ewma3', 'receiving_yards_after_catch_ewma3', 'def_allowed_l4w', 'fantasy_points_ppr_std5', 'prior_season_ppg'] for WRs.

The current workflow calculates predictions for players based on their stats over the past 3 games in such a way that performance 1 game prior carries slightly more worth than 2, 3, etc. It also factors in the strength of the defense they are going against and to some extent, how good the player has been historically. For example, if Ja'Marr Chase struggles the past 3 weeks, but sees an easy defense this current week, he will be projected to score a lot of points regardless given the strength of the defense and the fact that he is historically a very good player.

In [148]:
schedules = nfl.load_schedules(seasons=[2026]).to_pandas()
print(schedules.columns.tolist())
print(schedules[schedules.week == 10][['season', 'week', 'home_team', 'away_team']])

['game_id', 'season', 'game_type', 'week', 'gameday', 'weekday', 'gametime', 'away_team', 'away_score', 'home_team', 'home_score', 'location', 'result', 'total', 'overtime', 'old_game_id', 'gsis', 'nfl_detail_id', 'pfr', 'pff', 'espn', 'ftn', 'away_rest', 'home_rest', 'away_moneyline', 'home_moneyline', 'spread_line', 'away_spread_odds', 'home_spread_odds', 'total_line', 'under_odds', 'over_odds', 'div_game', 'roof', 'surface', 'temp', 'wind', 'away_qb_id', 'home_qb_id', 'away_qb_name', 'home_qb_name', 'away_coach', 'home_coach', 'referee', 'stadium_id', 'stadium']
     season  week home_team away_team
136    2026    10       NYG       WAS
137    2026    10       DET        NE
138    2026    10       ATL        KC
139    2026    10       CLE       HOU
140    2026    10        GB       MIN
141    2026    10       IND       MIA
142    2026    10        NO       CAR
143    2026    10       NYJ       BUF
144    2026    10       TEN       JAX
145    2026    10       ARI        LA
146    2026    10        LV       SEA
147    2026    10       DAL        SF
148    2026    10       CIN       PIT
149    2026    10       BAL       LAC